<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Determinant_of_Matrix_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
# Practice
import numpy as np
A = np.array([[1, 2, -1], [4, 6, -2], [-1, 3, 3]])
print(A, "\n")

print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]] 

-14
