<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
#Problem 1. Consider the four matrices. (20 points each)
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

print("MATRICES:\n")
print("A =\n", A)
print("B =\n", B)
print("C =\n", C)
print("D =\n", D, "\n")
print("PROBLEMS:\n")

# a. AB
a = np.dot(A, B)
print("a) AB:\n", a, "\n")

# b. D + D
b = np.add(D, D)
print("b) D + D:\n", b, "\n")

# c. 2C
c = np.dot(2, C)
print("c) 2C:\n", c, "\n")


MATRICES:

A =
 [[1 2 3]
 [4 5 6]]
B =
 [[1 2]
 [3 4]
 [5 6]]
C =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
D =
 [[1 2]
 [3 4]] 

PROBLEMS:

a) AB:
 [[22 28]
 [49 64]] 

b) D + D:
 [[2 4]
 [6 8]] 

c) 2C:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 



In [46]:
#Problem 2. Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python program. (40 points)
import numpy as np

A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

print("MATRICES:\n")
print("A =", A)
print("B =", B, "\n")
print("PROBLEM:\n")
print("Find the cross-product of matrices A and B:")

result = np.cross(A, B)
print("A x B =", result, "\n")

solution = [(A[1]*B[2])-(A[2]*B[1]), (A[2]*B[0])-(A[0]*B[2]), (A[0]*B[1])-(A[1]*B[0])]
print("SOLUTION:\n")
print("A x B = [(7 * 8)-(4 * 9), (4 * 3)-(2 * 8), (2 * 9)-(7 * 3)]")
print("A x B = [(56) - (36), (12) - (16), (18) - (21)]")
print("A x B =", solution)

MATRICES:

A = [2 7 4]
B = [3 9 8] 

PROBLEM:

Find the cross-product of matrices A and B:
A x B = [20 -4 -3] 

SOLUTION:

A x B = [(7 * 8)-(4 * 9), (4 * 3)-(2 * 8), (2 * 9)-(7 * 3)]
A x B = [(56) - (36), (12) - (16), (18) - (21)]
A x B = [20, -4, -3]
