<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations and Its Applications

In [28]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2, 0.2, 1])
C = np.array([-0.2, 2.1, -1.5])
print("Array A:\n", A, "\nArray B:\n", B, "\nArray C:\n", C)

sum = np.add(np.add(A,B), C)
diff = np.subtract(np.subtract(A,B), C)
prod = np.multiply(np.multiply(A,B), C)
quot = np.divide(np.divide(A,B), C)

print("\nAddition of Arrays (A+B+C):\n", sum)
print("Subtraction of Arrays (A-B-C):\n", diff)
print("Multiplication of Arrays (A*B*C):\n", prod)
print("Division of Arrays (A/B/C):\n", quot)

Array A:
 [[-0.4]
 [ 4.3]
 [-0.6]] 
Array B:
 [-0.2  0.2  1. ] 
Array C:
 [-0.2  2.1 -1.5]

Addition of Arrays (A+B+C):
 [[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]
Subtraction of Arrays (A-B-C):
 [[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]
Multiplication of Arrays (A*B*C):
 [[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]
Division of Arrays (A/B/C):
 [[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
