<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
A = np.array([
    [1,4],
    [0,3]
])
round(np.linalg.det(A))

3

In [24]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
round(np.linalg.det(B))

-235

In [26]:
#Associative Property
print("Associative Property: (AB)C = A(BC)")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6],[2,1,3],[9,7,8]])
C = np.array([[8,3,9],[2,8,4],[9,2,5]])
print("A:\n",A)
print("B:\n",B)
print("C:\n",C)

AB = np.dot(A,B)
ABC = np.dot(AB,C)
print("\n(AB)C = \n", ABC)

BC = np.dot(B,C)
BCA = np.dot(A,BC)
print("A(BC) = \n", BCA)

Associative Property: (AB)C = A(BC)
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[4 5 6]
 [2 1 3]
 [9 7 8]]
C:
 [[8 3 9]
 [2 8 4]
 [9 2 5]]

(AB)C = 
 [[ 660  401  607]
 [1557  950 1423]
 [2454 1499 2239]]
A(BC) = 
 [[ 660  401  607]
 [1557  950 1423]
 [2454 1499 2239]]


In [27]:
#Distributive Property
print("Distributive Property: A(B+C) = AB + AC")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6],[2,1,3],[9,7,8]])
C = np.array([[8,3,9],[2,8,4],[9,2,5]])
print("A:\n",A)
print("B:\n",B)
print("C:\n",C)

B_C = np.add(B,C)
AB_C = np.dot(A,B_C)
print("\nA(B+C) = \n", AB_C)

AB = np.dot(A,B)
AC = np.dot(A,C)
AB_AC = np.add(AB,AC)
print("AB + AC = \n", AB_AC)

Distributive Property: A(B+C) = AB + AC
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[4 5 6]
 [2 1 3]
 [9 7 8]]
C:
 [[8 3 9]
 [2 8 4]
 [9 2 5]]

A(B+C) = 
 [[ 74  53  68]
 [176 131 173]
 [278 209 278]]
AB + AC = 
 [[ 74  53  68]
 [176 131 173]
 [278 209 278]]


In [28]:
#Closure Property
print("Closure Property:\n" + "Multiplication of a scalar(a real number) c and matrix A with size m x n:\n" + "Resulting Matrix should also have the size m x n")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = 5
print("A:\n",A)
print("c:\n",c)

cA = np.dot(c,A)
print("\ncA = \n", cA)


Closure Property:
Multiplication of a scalar(a real number) c and matrix A with size m x n:
Resulting Matrix should also have the size m x n
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
c:
 5

cA = 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
#Multiplicative Identity Property
print("Multiplicative Identity Property:\n" + "The n x n identity")


#Dimension Property
#Multiplicative property of Zero
