<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations

Vector Addition

In [6]:
import numpy as np
A = np.array([1, 2, 0])
B = np.array([3, 1, -2])
C = np.array([0, 0, 1])

print(A + B + C)

print(np.add(A, np.add(B, C)))

print(np.sum(B))

[ 4  3 -1]
[ 4  3 -1]
2


Vector Subtraction

In [7]:
print(np.subtract(A, B))

print(A - B)

[-2  1  2]
[-2  1  2]


Vector Multiplication

In [8]:
print(np.multiply(A, B))

print(A * B)

[3 2 0]
[3 2 0]


Vector Division

In [10]:
print(np.divide(A, B))

print(A / B)

C = np.array([3.9, 1.8, 7.7])
D = np.array([1, 1, 1])
print(C // D)

np.array(A / B, dtype = int)

[ 0.33333333  2.         -0.        ]
[ 0.33333333  2.         -0.        ]
[3. 1. 7.]


array([0, 2, 0])