<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
round(np.linalg.det(A))

3

In [ ]:
## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
round(np.linalg.det(B))

-235

In [34]:
#Commutative Property
print("Commutative Property: AB is not equal BA")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6],[2,1,3],[9,7,8]])
print("A:\n",A)
print("B:\n",B)

AB = np.dot(A,B)
print("\nAB = \n", AB)

BA = np.dot(B,A)
print("BA = \n", BA)

Commutative Property: AB is not equal BA
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[4 5 6]
 [2 1 3]
 [9 7 8]]

AB = 
 [[ 35  28  36]
 [ 80  67  87]
 [125 106 138]]
BA = 
 [[ 66  81  96]
 [ 27  33  39]
 [ 93 117 141]]


In [ ]:
#Associative Property
print("Associative Property: (AB)C = A(BC)")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6],[2,1,3],[9,7,8]])
C = np.array([[8,3,9],[2,8,4],[9,2,5]])
print("A:\n",A)
print("B:\n",B)
print("C:\n",C)

AB = np.dot(A,B)
ABC = np.dot(AB,C)
print("\n(AB)C = \n", ABC)

BC = np.dot(B,C)
BCA = np.dot(A,BC)
print("A(BC) = \n", BCA)

Associative Property: (AB)C = A(BC)
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[4 5 6]
 [2 1 3]
 [9 7 8]]
C:
 [[8 3 9]
 [2 8 4]
 [9 2 5]]

(AB)C = 
 [[ 660  401  607]
 [1557  950 1423]
 [2454 1499 2239]]
A(BC) = 
 [[ 660  401  607]
 [1557  950 1423]
 [2454 1499 2239]]


In [ ]:
#Distributive Property
print("Distributive Property: A(B+C) = AB + AC")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[4,5,6],[2,1,3],[9,7,8]])
C = np.array([[8,3,9],[2,8,4],[9,2,5]])
print("A:\n",A)
print("B:\n",B)
print("C:\n",C)

B_C = np.add(B,C)
AB_C = np.dot(A,B_C)
print("\nA(B+C) = \n", AB_C)

AB = np.dot(A,B)
AC = np.dot(A,C)
AB_AC = np.add(AB,AC)
print("AB + AC = \n", AB_AC)

Distributive Property: A(B+C) = AB + AC
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[4 5 6]
 [2 1 3]
 [9 7 8]]
C:
 [[8 3 9]
 [2 8 4]
 [9 2 5]]

A(B+C) = 
 [[ 74  53  68]
 [176 131 173]
 [278 209 278]]
AB + AC = 
 [[ 74  53  68]
 [176 131 173]
 [278 209 278]]


In [ ]:
#Closure Property
print("Closure Property:\n" + "Multiplication of a scalar(a real number) c and matrix A with size m x n:\n" + "Resulting Matrix should also have the size m x n")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = 5
print("A:\n",A)
print("c:\n",c)

cA = np.dot(c,A)
print("\ncA = \n", cA)

Closure Property:
Multiplication of a scalar(a real number) c and matrix A with size m x n:
Resulting Matrix should also have the size m x n
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
c:
 5

cA = 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [32]:
#Multiplicative Identity Property
print("Multiplicative Identity Property: I = I, A = A\n" + "Where A is an n x n matrix and 'I' is an identity matrix of order n")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A:\n",A)
I = np.eye(3,3)
print("I:\n", I)

AI = np.dot(A,I)
print("\nAI = \n", AI, "\n = A")

Multiplicative Identity Property: I = I, A = A
Where A is an n x n matrix and 'I' is an identity matrix of order n
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

AI = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
 = A


In [33]:
#Multiplicative property of Zero
print("Multiplicative property of Zero:\n" + "If a matrix is multiplied by a zero matrix, the result matrix is a zero matrix")
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A:\n",A)
I = np.zeros([3,3])
print("I:\n", I)

AI = np.dot(A,I)
print("\nAI = \n", AI, "\n = I")

Multiplicative property of Zero:
If a matrix is multiplied by a zero matrix, the result matrix is a zero matrix
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
I:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

AI = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 = I
