<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [10]:
#Coding Activity 10
#Let x = price for flour per sack
#Let y = price for yeast per pack
#Let z = price for one piece of egg
import numpy as np
C = np.array([[30, 10, 120], [40, 20, 200], [50, 40, 360]])
C1 = np.array([[12500, 10, 120], [18000, 20, 200], [25700, 40, 360]])
C2 = np.array([[30, 12500, 120], [40, 18000, 200], [50, 25700, 360]])
C3 = np.array([[30, 10, 12500], [40, 20, 18000], [50, 40, 25700]])

print("C: \n", C, "\nC1: \n", C1, "\nC2: \n", C2, "\nC3: \n", C3, "\n")

cdet = round(np.linalg.det(C))
c1det = round(np.linalg.det(C1))
c2det = round(np.linalg.det(C2))
c3det = round(np.linalg.det(C3))

print("C Det =", cdet, "\nC1 Det =", c1det, "\nC2 Det =", c2det, "\nC3 Det =", c3det, "\n")

x = np.divide(c1det,cdet)
y = np.divide(c2det,cdet)
z = np.divide(c3det,cdet)
print("x = C1 Det/C Det =", x)
print("y = C2 Det/C Det =", y)
print("z = C3 Det/C Det =", z)

C: 
 [[ 30  10 120]
 [ 40  20 200]
 [ 50  40 360]] 
C1: 
 [[12500    10   120]
 [18000    20   200]
 [25700    40   360]] 
C2: 
 [[   30 12500   120]
 [   40 18000   200]
 [   50 25700   360]] 
C3: 
 [[   30    10 12500]
 [   40    20 18000]
 [   50    40 25700]] 

C Det = 4000 
C1 Det = 1320000 
C2 Det = 560000 
C3 Det = 40000 

x = C1 Det/C Det = 330.0
y = C2 Det/C Det = 140.0
z = C3 Det/C Det = 10.0
