<a href="https://colab.research.google.com/github/JustinCruz4133/58013-LinearAlgebra/blob/main/Vector%2C_Spaces_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector

In [2]:
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


Shape of the Matrix

In [28]:
#Checking shapes
#Shapes tells us how many rows and columns are there
#Size Dimensions, Size
import numpy as np
ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
print(ball1)
print(ball2)

b1 = np.shape(ball1)
b2 = np.shape(ball2)

print(b1 + b2)

x = np.ndim(ball1)
y = np.ndim(ball2)

print(x)
print(y)

#pool.shape

[1 2 3]
[ 0  1 -1]
[1 3 2]
(3, 3)
1
1


Spaces

In [34]:
#Addition
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])
R1 = A + B
R2 = np.add(A, B)

print(R1)
print(R2)

[ 6 -2]
[ 6 -2]


In [35]:
#Subtraction
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])
R1 = A - B
R2 = np.subtract(A, B)

print(R1)
print(R2)

[2 8]
[2 8]


In [50]:
#Scalar Product - Dot
import numpy as np
A = np.array([4, 3])
S = np.array([2])
#R1 = S * A
R2 = np.multiply(S, A)

#print(R1)
print(R2)

[8 6]


In [48]:
#Vector Product - Cross (MULTIPLY)
import numpy as np
A = np.array([4, 3])
B = np.array([[2], [-5]])
#R1 = A * B
R2 = np.multiply(A, B)

#print(R1)
print(R2)

[[  8   6]
 [-20 -15]]


In [61]:
#Property of Matrix

#Identity Matrix
c = np.eye(3, 3)
print(c)

#Zero Matrix
d = np.zeros([5, 5])
print(d)

#Full Matrix
e = np.full([3, 3], 7)
print(e)

#Transpose of Matrix
A = np.array([4, 3])
B = np.array([[2], [-5]])
R2 = np.multiply(A, B)

f = np.transpose(R2)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
